[book]
authors = ["Frozen String"]
language = "zh-cn"
multilingual = false
src = "src"
title = "ForzenString博客小站"
description = "闽ICP备2022002309号-1"

[build]
build-dir = "./output"
create-missing = true

[output.html]
default-theme = "rust"
mathjax-support = true
additional-css = []
additional-js = []
no-section-label = true

[output.html.print]
enable = false

[output.html.fold]
enable = true
level = 0        

[output.html.playground]
runnable = false
